In [1]:
import pandas as pd

df = pd.read_excel(r"D:\SURE\G34_Python\datasets\iris.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [3]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
#Data processing step
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df.drop(columns="variety"))

StandardScaler()

In [5]:
X = scaler.transform(df.drop(columns="variety"))
X.shape

(150, 4)

In [6]:
X = pd.DataFrame(X,columns=list(df.columns)[:-1])
X.head()

   sepal.length  sepal.width  petal.length  petal.width
0     -0.900681     1.019004     -1.340227    -1.315444
1     -1.143017    -0.131979     -1.340227    -1.315444
2     -1.385353     0.328414     -1.397064    -1.315444
3     -1.506521     0.098217     -1.283389    -1.315444
4     -1.021849     1.249201     -1.340227    -1.315444

In [7]:
df["variety"].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [8]:
#label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df["variety"])

LabelEncoder()

In [9]:
y = le.transform(df["variety"])
y.shape

(150,)

In [11]:
list(df.columns)[-1]

'variety'

In [18]:
le.inverse_transform([0,1,2])

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [17]:
import numpy as np
y = pd.Series(y)
y.value_counts()

0    50
1    50
2    50
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,shuffle=True)
X_train.shape, X_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [20]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [25]:
lr.coef_

array([[-1.02107426,  1.07849173, -1.8348776 , -1.68935525],
       [ 0.55610782, -0.36264703, -0.34863706, -0.72578357],
       [ 0.46496644, -0.7158447 ,  2.18351466,  2.41513882]])

In [26]:
lr.intercept_

array([-0.26449619,  1.93594193, -1.67144575])

P(y=setosa) = 1/(1+e^(-1.02107426(sepal.length)+1.07849173(sepal.width)-1.8348776(petal.length)-1.68935525(petal.width)-0.26449619))

P(y=Versicolor) = 1/(1+e^(0.55610782(sepal.length)-0.36264703(sepal.width)-0.34863706(petal.length)-0.72578357(petal.width)+1.93594193))

P(y=virginica) = 1/(1+e^(0.46496644(sepal.length)-0.7158447(sepal.width)2.18351466(petal.length)+2.41513882(petal.width)-1.67144575))

In [27]:
X_test[:2]

    sepal.length  sepal.width  petal.length  petal.width
9      -1.143017     0.098217     -1.283389    -1.447076
56      0.553333     0.558611      0.535409     0.527406

In [21]:
#Predictions

y_predictions = lr.predict(X_test)
y_predictions

array([0, 1, 1, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 0, 2, 1, 1, 2, 0, 0, 2,
       0, 1, 2, 1, 0, 0, 0, 2])

In [ ]:
le.inverse_transform(y_predictions) #predicted y-Values from LR ML model

array(['Setosa', 'Versicolor', 'Versicolor', 'Versicolor', 'Virginica',
       'Virginica', 'Versicolor', 'Virginica', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Virginica', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Setosa', 'Virginica', 'Setosa', 'Versicolor', 'Virginica',
       'Versicolor', 'Setosa', 'Setosa', 'Setosa', 'Virginica'],
      dtype=object)

In [ ]:
le.inverse_transform(y_test) #Actual y- values from the original data

array(['Setosa', 'Versicolor', 'Versicolor', 'Versicolor', 'Virginica',
       'Virginica', 'Versicolor', 'Virginica', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Virginica', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Setosa', 'Virginica', 'Setosa', 'Versicolor', 'Virginica',
       'Versicolor', 'Setosa', 'Setosa', 'Setosa', 'Virginica'],
      dtype=object)