In [2]:
import pandas as pd 
df=pd.DataFrame({"id":[1,2,3]})

In [3]:
df

   id
0   1
1   2
2   3

In [8]:
df2=pd.DataFrame([[1,2,3,4,5],[10,20,30,40,50,]],index=["a","b"],columns=["col1","col2","col3","col4","col5"])
df2

   col1  col2  col3  col4  col5
a     1     2     3     4     5
b    10    20    30    40    50

In [13]:
import pandas as pd 
df1=pd.read_csv(r"C:\Users\ashok\Downloads\merged.csv")

C:\Users\ashok\AppData\Local\Temp\ipykernel_19868\3747629557.py:2: DtypeWarning: Columns (595,600,603,605,606,617,620) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"C:\Users\ashok\Downloads\merged.csv")

In [14]:
df1

,sample-id,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Bacteroidaceae;g__Bacteroides,d__Bacteria;p__Firmicutes;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;g__Agathobacter,d__Bacteria;p__Firmicutes;c__Clostridia;o__Lachnospirales;f__Lachnospiraceae;__,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Prevotellaceae;g__Prevotella_9,d__Bacteria;p__Bacteroidota;c__Bacteroidia;o__Bacteroidales;f__Rikenellaceae;g__Alistipes,d__Bacteria;p__Firmicutes;c__Clostridia;o__Oscillospirales;f__Ruminococcaceae;g__Faecalibacterium,d__Bacteria;p__Actinobacteriota;c__Actinobacteria;o__Bifidobacteriales;f__Bifidobacteriaceae;g__Bifidobacterium,d__Bacteria;p__Firmicutes;c__Clostridia;o__Peptostreptococcales-Tissierellales;f__Peptostreptococcaceae;g__uncultured,d__Bacteria;p__Firmicutes;c__Negativicutes;o__Veillonellales-Selenomonadales;f__Selenomonadaceae;g__Megamonas,...,Constipation_GSRS-IBS,Diarrhea_GSRS-IBS,Satiety_GSRS-IBS,GSRS Total Score,HAD: Anxiety score,HAD: Depression score,Rome II Subtype,SF36:Mental Component,SF36: Physical Component,broad-scale environmental context
0,SRR8417456,45.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediterranean
1,SRR8417582,27.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediterranean
2,SRR8417405,12.0,0.0,0.0,11.0,0.0,59.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediterranean
3,SRR8417478,217.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediterranean
4,SRR8417409,100.0,65.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediterranean
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,SRR18588556,41570.0,135.0,2.0,8.0,10302.0,35282.0,5147.0,99.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,SRR18588891,146562.0,1.0,2.0,33.0,1199.0,2137.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1023,SRR18589003,48447.0,7.0,143.0,27933.0,25059.0,6645.0,4080.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,SRR18588629,218122.0,70.0,24.0,92.0,19.0,11255.0,565.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025,SRR18588370,266768.0,174.0,0.0,4418.0,291.0,49282.0,70.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN